<h1>Meu Primeiro Hello World!</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>SKU</th>
            <th>Peso</th>
            <th>Preço</th>
            <th>Descrição</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product){
            echo "
            <tr>
                <td>{$product['entity_id']}</td>
                <td>{$product['meta_title']}</td>
                <td>{$product['sku']}</td>
                <td>{$product['weight']}</td>
                <td>{$product['price']}</td>
                <td>{$product['meta_description']}</td>
            </tr>";
        }
        ?>
    </tbody>
</table>

